language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -U pip setuptools pipenv
  - pipenv --bare install

script:
  - rm -rf dist && python setup.py sdist && pip install dist/*.tar.gz
  - pytest -v
  - pylama
