up:
  - python: 3.6.4
  - pipfile

commands:
  lint:
    run: pylint --rcfile=pylintrc setup.py appsecrets
  typing:
    run: mypy appsecrets
  clean:
    run: find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
  test:
    run: pytest -v
  release:
    run: pyreleaser create --only-on master --push
  publish:
    run: pyreleaser upload
