up:
  - python: 3.6.4
  - custom:
      met?: pipenv --bare sync
      meet: pip install pipenv && pipenv --bare sync
  - custom:
      name: Install project in develop mode
      met?: pip show appsecrets > /dev/null 2> /dev/null
      meet: pip install -e .

commands:
  lint:
    run: pylint --rcfile=pylintrc setup.py appsecrets
  clean:
    run: find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
  test:
    run: pytest -v
  release:
    run: pyreleaser create --only-on master --push
  publish:
    run: pyreleaser upload
