up:
  - python: 3.6.4
  - custom:
      met?: pipenv --bare sync
      meet: pip install pipenv && pipenv --bare sync
  - custom:
      name: Install project in develop mode
      met?: pip show appsecrets 2> /dev/null
      meet: pip install -e .

commands:
  lint:
    run: pylama
  clean:
    run: find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
  test:
    run: pytest -v
